# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: photo_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'photo_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13photo_service.proto\x12\x05photo\"\xa1\x01\n\x11PlacePhotoRequest\x12\x12\n\nphoto_data\x18\x01 \x01(\x0c\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\x12$\n\nplace_info\x18\x04 \x01(\x0b\x32\x10.photo.PlaceInfo\x12\x12\n\nsource_app\x18\x05 \x01(\t\x12\x16\n\x0esource_user_id\x18\x06 \x01(\t\"\x96\x01\n\tPlaceInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x04 \x01(\t\x12\x10\n\x08latitude\x18\x05 \x01(\x01\x12\x11\n\tlongitude\x18\x06 \x01(\x01\x12\x17\n\x0fgoogle_place_id\x18\x07 \x01(\t\x12\r\n\x05types\x18\x08 \x03(\t\"{\n\x12PlacePhotoResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x11\n\tphoto_url\x18\x02 \x01(\t\x12\x10\n\x08photo_id\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\x12\x18\n\x10matched_place_id\x18\x05 \x01(\t\"o\n\x12\x42\x61tchPhotoResponse\x12\x15\n\rsuccess_count\x18\x01 \x01(\x05\x12\x14\n\x0c\x66\x61iled_count\x18\x02 \x01(\x05\x12,\n\tresponses\x18\x03 \x03(\x0b\x32\x19.photo.PlacePhotoResponse2\xa7\x01\n\x0cPhotoService\x12G\n\x10UploadPlacePhoto\x12\x18.photo.PlacePhotoRequest\x1a\x19.photo.PlacePhotoResponse\x12N\n\x15UploadPlacePhotoBatch\x12\x18.photo.PlacePhotoRequest\x1a\x19.photo.BatchPhotoResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'photo_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLACEPHOTOREQUEST']._serialized_start=31
  _globals['_PLACEPHOTOREQUEST']._serialized_end=192
  _globals['_PLACEINFO']._serialized_start=195
  _globals['_PLACEINFO']._serialized_end=345
  _globals['_PLACEPHOTORESPONSE']._serialized_start=347
  _globals['_PLACEPHOTORESPONSE']._serialized_end=470
  _globals['_BATCHPHOTORESPONSE']._serialized_start=472
  _globals['_BATCHPHOTORESPONSE']._serialized_end=583
  _globals['_PHOTOSERVICE']._serialized_start=586
  _globals['_PHOTOSERVICE']._serialized_end=753
# @@protoc_insertion_point(module_scope)
